Repository BME-MIT-IET/iet-hf-2024-fantasztikus_otos, pull requests merged in 2024-05, with the labels that each got.

#19 Fixed syntax in build.gradle
  build.gradle
Labels: bug

#22 Add gradle build action
  .github/workflows/gradle.yml
  .github/workflows/sonar.yml
Labels: enhancement

#34 OSHI Implementation
  .idea/modules.xml
  build.gradle
  src/main/java/Osztalyok/Field.java
  src/main/java/Osztalyok/SystemMonitor.java
Labels: enhancement

#38 Param for LoadMap
  .idea/modules.xml
  src/main/java/Osztalyok/Field.java
  src/main/java/main/FoMenu.java
  src/test/java/Osztalyok/StepDefinitions/StepDefinitionsBreakPump.java
  src/test/java/Osztalyok/StepDefinitions/StepDefinitionsComplexTest1.java
  src/test/java/Osztalyok/StepDefinitions/StepDefinitionsGameEnd.java
  src/test/java/Osztalyok/StepDefinitions/StepDefinitionsHole.java
  src/test/java/Osztalyok/StepDefinitions/StepDefinitionsRetoolPump.java
  src/test/java/Osztalyok/StepDefinitions/StepDefinitionsStickyPipe.java
Labels: documentation
